// <auto-generated />
using System;
using CalculadoraSYNECO.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalculadoraSYNECO.Migrations
{
    [DbContext(typeof(CalculadoraSYNECOContext))]
    partial class CalculadoraSYNECOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CalculadoraSYNECO.Models.Calculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Numero1")
                        .HasColumnType("float");

                    b.Property<double?>("Numero2")
                        .HasColumnType("float");

                    b.Property<int>("Operacao")
                        .HasColumnType("int");

                    b.Property<double?>("Resultado")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calculo");
                });
#pragma warning restore 612, 618
        }
    }
}
